### Step - 1 Find Business Problems

---

## My task is to analyze the data and provide actionable recommendations to improve profitability and customer satisfaction.

---

# Business Questions to Solve 

---

### Revenue Analysis

---
* Which region generates the highest revenue?
* Which customer segment contributes the most revenue?
* Which sales channel performs best?

### Profitability Analysis

---
* Which region has the highest profit?
* Which product category is the most profitable?
* Are there any regions generating high revenue but low profit?

### Customer Analysis

---
* Which customer segment has the highest satisfaction score?
* Does higher customer satisfaction appear to correlate with higher profit?
* Which sales channel has the happiest customers?

### Strategic Recommendations

---
* Which region should receive more investment?
* Which product category should be promoted?
* Which customer segment should be targeted for growth?
* What actions would you recommend to increase profitability?

## Step - 2 Import Neccessary libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

## Step - 3 Load dataset 

---

In [3]:
df = pd.read_csv("business_analyst_case_study_dataset.csv")

In [4]:
df

,Transaction_ID,Region,Customer_Segment,Sales_Channel,Product_Category,Revenue,Cost,Profit,Customer_Satisfaction
0,T001,North,Consumer,Partner,Standard,21049,11351,9698,66
1,T002,North,Small Business,Retail,Basic,6952,3388,3564,74
2,T003,North,Small Business,Online,Premium,47590,34765,12825,86
3,T004,South,Corporate,Partner,Standard,5425,4087,1338,70
4,T005,West,Corporate,Retail,Basic,19110,15916,3194,81
...,...,...,...,...,...,...,...,...,...
95,T096,South,Small Business,Online,Premium,7638,5741,1897,75
96,T097,South,Consumer,Partner,Basic,20633,10326,10307,67
97,T098,South,Corporate,Partner,Standard,29175,15086,14089,98
98,T099,North,Consumer,Retail,Basic,42924,19756,23168,79
99,T100,West,Corporate,Partner,Basic,9980,6854,3126,100

## Step - 4 Basic data overview

---

In [5]:
df.shape

(100, 9)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Transaction_ID         100 non-null    object
 1   Region                 100 non-null    object
 2   Customer_Segment       100 non-null    object
 3   Sales_Channel          100 non-null    object
 4   Product_Category       100 non-null    object
 5   Revenue                100 non-null    int64
 6   Cost                   100 non-null    int64
 7   Profit                 100 non-null    int64
 8   Customer_Satisfaction  100 non-null    int64
dtypes: int64(4), object(5)
memory usage: 7.2+ KB

In [7]:
df.size

900

In [8]:
df.dtypes

Transaction_ID           object
Region                   object
Customer_Segment         object
Sales_Channel            object
Product_Category         object
Revenue                   int64
Cost                      int64
Profit                    int64
Customer_Satisfaction     int64
dtype: object

##  STEP - 5 EDA (EXPLORATORY DATA ANALYSIS)

---

In [10]:
df.head(2)

,Transaction_ID,Region,Customer_Segment,Sales_Channel,Product_Category,Revenue,Cost,Profit,Customer_Satisfaction
0,T001,North,Consumer,Partner,Standard,21049,11351,9698,66
1,T002,North,Small Business,Retail,Basic,6952,3388,3564,74

In [11]:
df.isna().sum()

Transaction_ID           0
Region                   0
Customer_Segment         0
Sales_Channel            0
Product_Category         0
Revenue                  0
Cost                     0
Profit                   0
Customer_Satisfaction    0
dtype: int64

In [13]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Revenue,100.0,26930.80,13817.801813,5110.0,15358.25,25272.5,39243.5,49676.0
Cost,100.0,17820.64,9681.742472,3105.0,9905.25,16727.0,24063.5,40563.0
Profit,100.0,9110.16,5958.654710,1302.0,4389.50,8449.0,12875.5,26123.0
Customer_Satisfaction,100.0,80.66,11.696689,60.0,71.75,81.5,92.0,100.0

In [14]:
df.describe(include="object")

       Transaction_ID Region Customer_Segment Sales_Channel Product_Category
count             100    100              100           100              100
unique            100      4                3             3                3
top              T001  South         Consumer       Partner            Basic
freq                1     32               38            34               42

In [17]:
for i in df.select_dtypes(include="object").columns:
    print(df[i].value_counts())
    print("***"*10)

Transaction_ID
T001    1
T064    1
T074    1
T073    1
T072    1
       ..
T031    1
T030    1
T029    1
T028    1
T100    1
Name: count, Length: 100, dtype: int64
******************************
Region
South    32
West     25
East     22
North    21
Name: count, dtype: int64
******************************
Customer_Segment
Consumer          38
Corporate         33
Small Business    29
Name: count, dtype: int64
******************************
Sales_Channel
Partner    34
Retail     33
Online     33
Name: count, dtype: int64
******************************
Product_Category
Basic       42
Standard    31
Premium     27
Name: count, dtype: int64
******************************

---
 
 ###  Revenue Analysis

 ---
* Which region generates the highest revenue?
* Which customer segment contributes the most revenue?
* Which sales channel performs best?

In [18]:
df.head(1)

,Transaction_ID,Region,Customer_Segment,Sales_Channel,Product_Category,Revenue,Cost,Profit,Customer_Satisfaction
0,T001,North,Consumer,Partner,Standard,21049,11351,9698,66

In [19]:
# Which region generates the highest revenue?
df.groupby("Region")["Revenue"].mean()

Region
East     26258.772727
North    28926.142857
South    27087.093750
West     25646.040000
Name: Revenue, dtype: float64

In [20]:
# Which customer segment contributes the most revenue?
df.groupby("Customer_Segment")["Revenue"].mean()

Customer_Segment
Consumer          26942.078947
Corporate         27956.030303
Small Business    25749.379310
Name: Revenue, dtype: float64

In [21]:
# Which sales channel performs best?
df.groupby("Sales_Channel")["Profit"].mean()

Sales_Channel
Online      8085.636364
Partner    10263.735294
Retail      8946.151515
Name: Profit, dtype: float64

---

## Profitability Analysis

---

* Which region has the highest profit?
* Which product category is the most profitable?
* Are there any regions generating high revenue but low profit?

In [23]:
df.head(2)

,Transaction_ID,Region,Customer_Segment,Sales_Channel,Product_Category,Revenue,Cost,Profit,Customer_Satisfaction
0,T001,North,Consumer,Partner,Standard,21049,11351,9698,66
1,T002,North,Small Business,Retail,Basic,6952,3388,3564,74

In [29]:
# Which region has the highest profit?
df.groupby("Region")["Profit"].sum()

Region
East     225486
North    212279
South    291456
West     181795
Name: Profit, dtype: int64

In [26]:
# Which product category is the most profitable?
df.groupby("Product_Category")["Profit"].mean()

Product_Category
Basic       9395.428571
Premium     8959.407407
Standard    8854.967742
Name: Profit, dtype: float64

In [32]:
# Are there any regions generating high revenue but low profit?
df.groupby("Region")[["Revenue","Profit"]].sum()

        Revenue  Profit
Region
East     577693  225486
North    607449  212279
South    866787  291456
West     641151  181795

---

---

## Customer Analysis

---
* Which customer segment has the highest satisfaction score?
* Does higher customer satisfaction appear to correlate with higher profit?
* Which sales channel has the happiest customers?

In [33]:
# Which customer segment has the highest satisfaction score?
df.groupby("Customer_Segment")["Customer_Satisfaction"].sum()

Customer_Segment
Consumer          3068
Corporate         2721
Small Business    2277
Name: Customer_Satisfaction, dtype: int64

In [34]:
df.head(1)

,Transaction_ID,Region,Customer_Segment,Sales_Channel,Product_Category,Revenue,Cost,Profit,Customer_Satisfaction
0,T001,North,Consumer,Partner,Standard,21049,11351,9698,66

In [36]:
# Does higher customer satisfaction appear to correlate with higher profit?
df["Customer_Satisfaction"].corr(df["Profit"])

np.float64(0.03283012648086079)

In [39]:
# Which sales channel has the happiest customers?
df.groupby('Sales_Channel')['Customer_Satisfaction'].mean()

Sales_Channel
Online     77.575758
Partner    82.176471
Retail     82.181818
Name: Customer_Satisfaction, dtype: float64

---

---

## Strategic Recommendations

---
* Which region should receive more investment?
* Which product category should be promoted?
* Which customer segment should be targeted for growth?
* What actions would you recommend to increase profitability?

In [40]:
# Which region should receive more investment?
df.groupby("Region")[["Revenue","Profit"]].sum()

        Revenue  Profit
Region
East     577693  225486
North    607449  212279
South    866787  291456
West     641151  181795

In [41]:
df.groupby("Region")[["Profit"]].mean()

              Profit
Region
East    10249.363636
North   10108.523810
South    9108.000000
West     7271.800000

In [44]:
df.groupby("Region")[["Revenue","Profit","Cost"]].sum()

        Revenue  Profit    Cost
Region
East     577693  225486  352207
North    607449  212279  395170
South    866787  291456  575331
West     641151  181795  459356

In [48]:
df['profit_margin'] = (df['Profit'] / df['Revenue']) * 100

In [50]:
df['profit_margin'].describe()

count    100.000000
mean      33.600935
std       10.721767
min       15.029955
25%       25.625022
50%       32.094933
75%       43.100773
max       53.974466
Name: profit_margin, dtype: float64

In [51]:
df.groupby('Region')['profit_margin'].mean().sort_values(ascending=False)

Region
East     37.547884
North    36.074034
South    33.478185
West     28.207336
Name: profit_margin, dtype: float64

In [59]:
# Which product category should be promoted?
df.groupby("Product_Category")["Profit"].sum()

Product_Category
Basic       394608
Premium     241904
Standard    274504
Name: Profit, dtype: int64

In [60]:
df.head(1)

,Transaction_ID,Region,Customer_Segment,Sales_Channel,Product_Category,Revenue,Cost,Profit,Customer_Satisfaction,profit_margin
0,T001,North,Consumer,Partner,Standard,21049,11351,9698,66,46.073448

In [62]:
# Which customer segment should be targeted for growth?
df.groupby("Customer_Segment")["Profit"].sum()

Customer_Segment
Consumer          381185
Corporate         310107
Small Business    219724
Name: Profit, dtype: int64

In [ ]:
# What actions would you recommend to increase profitability?

# Recommendation

---

* Reduce cost in inefficient segments
* Focus on high-margin regions/products
* Fix low-performing sales channels
* Target high-value customer segments

---